@startuml
HttpClientRibbonCommandFactory --> HttpClientRibbonCommandFactory:create() 创建hystrix命令
HttpClientRibbonCommandFactory -->HttpClientRibbonCommandFactory: new ReHttpClientRibbonCommand,serviceId作为commandKey
HttpClientRibbonCommandFactory -->HttpClientRibbonCommand:super()
AbstractRibbonCommand -->AbstractRibbonCommand:getSetter()
HttpClientRibbonCommand -->AbstractRibbonCommand:createSetter()
AbstractRibbonCommand -->AbstractRibbonCommand:getHystrixTimeout()计算超时时间
AbstractRibbonCommand -->AbstractRibbonCommand:getRibbonTimeout()
AbstractRibbonCommand -->AbstractRibbonCommand:初始化隔离策略
HttpClientRibbonCommand -->AbstractCommand:initCommandProperties()初始化命令属性
AbstractCommand -->AbstractCommand:initThreadPoolKey()初始化线程池key(以服务名称或自己重写)
AbstractCommand -->AbstractCommand:initMetrics()以commandKey(serviceId)维度创建测量器
AbstractCommand -->AbstractCommand:initCircuitBreaker()初始化熔断器
AbstractCommand -->AbstractCommand:initThreadPool()以服务的维度创建线程池
AbstractCommand -->AbstractCommand:initExecutionHook()拆行勾子
@enduml