@startuml
Application -> EurekaServerAutoConfiguration:run 服务启动
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:eurekaServerConfig()初始化服务端配置\n(EurekaServerConfigBean)
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:jerseyApplication()初始化jersey
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:peerAwareInstanceRegistry()节点例实注册器
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:peerEurekaNodes(）
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:eurekaServerContext()服务端context初始化
DefaultEurekaServerContext --> DefaultEurekaServerContext:initialize()context开始初始化
DefaultEurekaServerContext --> PeerEurekaNodes:start()定时刷新其它eureka节点信息
DefaultEurekaServerContext --> DefaultEurekaServerContext:init()
EurekaServerAutoConfiguration --> EurekaServerAutoConfiguration:eurekaServerBootstrap()创建bootstrap
EurekaServerAutoConfiguration --> EurekaServerInitializerConfiguration:start()
EurekaServerAutoConfiguration --> EurekaServerBootstrap:contextInitialized()
EurekaServerBootstrap --> EurekaServerBootstrap:initEurekaEnvironment()
EurekaServerBootstrap --> EurekaServerBootstrap:initEurekaServerContext()
EurekaServerBootstrap --> InstanceRegistry:syncUp()主动同步其它节点服务实例信息
EurekaServerBootstrap --> InstanceRegistry:openForTraffic()开启eureka节点间信息处理
InstanceRegistry -->InstanceRegistry:postInit()无效实例剔除
@enduml