@startuml
Application -> EurekaClientAutoConfiguration:run 服务启动
EurekaClientAutoConfiguration --> EurekaClientAutoConfiguration:eurekaInstanceConfigBean()\n初始化instance信息ip、port等信息
RefreshableEurekaClientConfiguration --> RefreshableEurekaClientConfiguration:eurekaClient() 初始化注册信息
RefreshableEurekaClientConfiguration --> RefreshableEurekaClientConfiguration:new CloudEurekaClient(）
RefreshableEurekaClientConfiguration --> CloudEurekaClient:
CloudEurekaClient --> CloudEurekaClient:register() 注册当前服务到注册中心
CloudEurekaClient --> CloudEurekaClient:initScheduledTasks()初始化定时任务\n(创建定时刷新服务列任务、创建心跳定时任务)
CloudEurekaClient --> EurekaServer:通过http向服务端发送注册信息
EurekaServer --> ApplicationResource:addInstance()添加服务实例信息
ApplicationResource --> InstanceRegistry:register()
InstanceRegistry --> InstanceRegistry:super.register()把实例信息保存到\n map<serviceId,List<Instance>>缓存中
InstanceRegistry -->  InstanceRegistry:replicateToPeers()把服务实例信息同步到其它eureka server节点
@enduml