@startuml
main ->RibbonLoadBalancerClient:execute()
RibbonLoadBalancerClient ->RibbonLoadBalancerClient:getLoadBalancer() 获取ILoadBalancer的实现
RibbonLoadBalancerClient -> RibbonLoadBalancerClient:getServer()通过loadbalancer 选出一个服务实例
LoadBalancerRequest -> LoadBalancerRequest:apply(instance)执行选择实例接口

main<-SpringClientFactory
main->ZoneAwareLoadBalancer:chooseServer()选择一个实例，如果配置了多区域机房则优化选择同机房的实例
ZoneAwareLoadBalancer->ZoneAvoidanceRule:choose
ZoneAvoidanceRule -> CompositePredicate: chooseRoundRobinAfterFiltering()通过过滤掉部分server,\n再选择
CompositePredicate-> CompositePredicate: getEligibleServers

@enduml