@startuml
Application ->RibbonAutoConfiguration:run()应用启动
RibbonAutoConfiguration->RibbonAutoConfiguration:springClientFactory()\nspring Application工厂,\n到时为以被调用服务名称\n创建一个对应的application,\n用于初始化服务对应的ribbon配置
RibbonAutoConfiguration->RibbonAutoConfiguration:loadBalancerClient()
Application->LoadBalancerAutoConfiguration:construct
LoadBalancerAutoConfiguration->LoadBalancerAutoConfiguration:loadBalancerRequestFactory()
RibbonClientConfiguration->RibbonClientConfiguration:ribbonClientConfig()配置初始化
Application->EurekaRibbonClientConfiguration:construct
EurekaRibbonClientConfiguration->EurekaRibbonClientConfiguration:ribbonPing()
EurekaRibbonClientConfiguration->EurekaRibbonClientConfiguration:->ribbonServerList()构建获取服务信息对象
EurekaRibbonClientConfiguration->DiscoveryEnabledNIWSServerList:construct 作为服务发现
DiscoveryEnabledNIWSServerList->DiscoveryEnabledNIWSServerList:initWithNiwsConfig
EurekaRibbonClientConfiguration->DomainExtractingServerList:construct()内部维护DiscoveryEnabledNIWSServerList实例，\n最终loadbalancer获取服务实例列表
RibbonClientConfiguration->DefaultClientConfigImpl:loadProperties()加截配置
HttpClientRibbonConfiguration->HttpClientRibbonConfiguration:httpClientConnectionManager()\n初始化httpclientMananger\n(默认使用httpClient,也可以配置okhttp等）
RibbonClientConfiguration->RibbonClientConfiguration:ribbonServerListFilter()
RibbonClientConfiguration->RibbonClientConfiguration:ribbonRule()创建负载规则
RibbonClientConfiguration->RibbonClientConfiguration:ribbonLoadBalancer()
RibbonClientConfiguration->ZoneAwareLoadBalancer:construct
ZoneAwareLoadBalancer->ZoneAwareLoadBalancer:restOfInit()
ZoneAwareLoadBalancer->ZoneAwareLoadBalancer:updateListOfServers()更新服务实例
RibbonClientConfiguration->RibbonClientConfiguration:ribbonPing()
RibbonClientConfiguration->RibbonClientConfiguration:ribbonLoadBalancingHttpClient
RibbonClientConfiguration->RibbonLoadBalancingHttpClient:construct
RibbonLoadBalancingHttpClient->RibbonLoadBalancingHttpClient:initWithNiwsConfig(config)配置timeout等信息
RibbonClientConfiguration->RibbonClientConfiguration:ribbonLoadBalancerContext()到些基本初化完成
@enduml